// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlite

import (
	"database/sql"
	"time"
)

type Package struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Private       bool           `json:"private"`
	Description   sql.NullString `json:"description"`
	Homepage      sql.NullString `json:"homepage"`
	Repository    sql.NullString `json:"repository"`
	Documentation sql.NullString `json:"documentation"`
	Topics        sql.NullString `json:"topics"`
	DownloadCount int64          `json:"download_count"`
	LikeCount     int64          `json:"like_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type PackageUploader struct {
	PackageID sql.NullInt64 `json:"package_id"`
	Uploader  string        `json:"uploader"`
}

type PackageVersion struct {
	ID            int64          `json:"id"`
	PackageID     int64          `json:"package_id"`
	Version       string         `json:"version"`
	Description   sql.NullString `json:"description"`
	PubspecYaml   string         `json:"pubspec_yaml"`
	Readme        sql.NullString `json:"readme"`
	Changelog     sql.NullString `json:"changelog"`
	ArchivePath   string         `json:"archive_path"`
	ArchiveSha256 sql.NullString `json:"archive_sha256"`
	Uploader      sql.NullString `json:"uploader"`
	Retracted     bool           `json:"retracted"`
	DownloadCount int64          `json:"download_count"`
	CreatedAt     time.Time      `json:"created_at"`
}
